[tool.poetry]
name = "tablelinker-lib"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "tablelinker_lib"}]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
jeraconv = "^0.2.1"
jageocoder = "^1.3.1"
requests = "^2.28.1"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
